skysky44/ieum

posts/templates/posts/index.html, static/base/css/base.css, static/posts/css/index.css, static/posts/js/index.js
- posts/index.html
navbar, toggle, 메인화면 디자인
=> [UPDATE] feature/posts_index.html

static/base/css/reset.css, templates/base.html
=> [UPDATE] base.html

my_messages/templates/my_messages/view.html, my_messages/views.py
=> [UPDATE] messages reply

accounts/views.py
음원 삭제/ 음원 바꿀때 media 이미지 자동 삭제 기능
=> [Update]profile/music/delete

my_messages/templates/my_messages/inbox.html
=> [ADD messages button

accounts/forms.py, accounts/templates/accounts/profile.html, accounts/templates/accounts/update.html, my_messages/templates/my_messages/compose.html, my_messages/templates/my_messages/received_messages.html, my_messages/templates/my_messages/sent_messages.html, my_messages/templates/my_messages/view.html, my_messages/views.py, posts/forms.py, posts/templates/posts/update.html, static/accounts/css/update.css, static/my_messages/css/compose.css, static/my_messages/css/received_messages.css, static/my_messages/css/sent_messages.css, static/my_messages/css/view.css, static/posts/css/update.css
- posts/update.html, accounts/update.html
레이아웃
- my_messages
레이아웃
=> [UPDATE] update/message.html

chat/consumers.py, chat/models.py, chat/templates/chat/index.html, chat/templates/chat/room.html, chat/urls.py, chat/views.py
=> [UPDATE] chat-room-delete-authority

accounts/templates/accounts/profile.html, accounts/views.py
=> [UPDATE]profile-follow-axious

posts/templates/posts/anonymous_detail.html, posts/templates/posts/detail.html, posts/views.py
detail과 anonymous_detail에 게시물 신고랑 댓글 신고 모달창 구현
=> [UPDATE] modal_report

accounts/templates/accounts/profile.html, static/accounts/css/profile.css
- accounts/profile.html
레이아웃, 반응형, 피드 모달 추가, 프로필 음악 버튼 로그인한 유저가 아닐 때 disabled 처리,
신고 당한 게시물, 댓글 => 로그인한 유저가 신고 대상과 동일하다면 해당 유저만 보이게함
로그인한 유저가 관리자인 경우 => 신고 당한 게시물과 댓글만 보이게함
=> [UPDATE] accounts/profile

posts/templates/posts/anonymous.html, posts/templates/posts/index.html, posts/views.py, static/posts/css/anonymous.css, static/posts/css/index.css
=> [UPDATE] posts/index.html, anonymous.html

my_messages/views.py, paints/templates/paints/create.html, paints/views.py
그림판 이미지 수정 작성자만 가능하도록 수정
그림판 완성 제출 후 확인 버튼 누르면 그림판 index로 이동
메시지 전송후 리다이렉트 경로 수정(보낸 편지함으로)
=> [UPDATE] paints&my_messages-detail-fix

accounts/views.py, my_messages/templates/my_messages/view.html, my_messages/views.py, requirements.txt
=> [FIXED]Fixed/messages

my_messages/templates/my_messages/view.html
마이페이지 프로필 음악 저장 버튼 가독성
회원정보 수정시 자기소개 문장 출력
댓글 좋아요 1개이상 일때 출력
index관련 이미지 추출
=> [FIXED]Fixed/all

a_ieum/settings.py, paints/templates/paints/index.html, posts/forms.py, posts/templates/posts/anonymous.html, posts/templates/posts/anonymous_create.html, posts/templates/posts/anonymous_detail.html, posts/templates/posts/anonymous_update.html, posts/templates/posts/create.html, posts/templates/posts/detail.html, posts/templates/posts/index.html, posts/templates/posts/update.html, posts/views.py, static/home/css/home.css, static/posts/css/anonymous.css, static/posts/css/class.css, static/posts/css/create.css, static/posts/css/index.css, static/posts/css/update.css, templates/home.html
=> [UPDATE]posts_index_anonymous

posts/forms.py, posts/templates/posts/main_search_results.html, posts/urls.py, posts/views.py, templates/base.html
=> [ADD] search navbar

posts/templates/posts/detail.html, posts/templates/posts/index.html, posts/views.py, static/posts/js/detail_comment_create_ajax.js, static/posts/js/detail_comment_likes_ajax.js, static/posts/js/detail_likes_ajax.js
posts 게시글 좋아요 비동기
posts 게시글 댓글 create 비동기
posts 게시글 댓글 좋아요 비동기
=> [UPDATE]posts/ajax

posts/views.py
=> [UPDATE] posts-views-count-2

accounts/templates/accounts/signup.html
=> [UPDATE] signup-double-check

posts/templates/posts/detail.html, posts/views.py
=> [ADD]posts/detail/next

my_messages/templates/my_messages/compose.html, my_messages/templates/my_messages/received_messages.html, my_messages/templates/my_messages/received_view.html, my_messages/templates/my_messages/sent_messages.html, my_messages/templates/my_messages/sent_view.html
=> [UPDATE] my_messages-name

accounts/templates/accounts/profile.html, static/accounts/css/profile.css
=> [UPDATE] profile.html

paints/templates/paints/create.html, paints/templates/paints/index.html, paints/templates/paints/update.html, static/base/css/reset.css, static/paints/css/create.css, static/posts/css/update.css
=> [UPDATE]paints/create_update

accounts/templates/accounts/update.html, static/accounts/css/update.css
=> [UPDATE] accounts/update.html

accounts/templates/accounts/balances.html, accounts/urls.py, accounts/views.py, paints/templates/paints/index.html
로그인후 word 값이 없다면 balances.html로 이동 기능
=> [ADD]balances/html

posts/templates/posts/anonymous_create.html, posts/templates/posts/anonymous_update.html, posts/templates/posts/create.html, posts/templates/posts/update.html, static/posts/css/create.css, static/posts/css/update.css
=> [UPDATE] update.html

static/base/css/common.css, templates/base.html
=> [ADD] base chat button

accounts/templates/accounts/signup.html, static/accounts/css/signup.css
=> [UPDATE] signup.html

chat/templates/chat/room.html, static/chat/css/room.css
=> [UPDATE] chat/room.html

posts/templates/posts/detail.html
=> [FIXED]detail/modal

accounts/templates/accounts/profile.html, static/accounts/css/profile.css, templates/base.html
=> [UPDATE]profile

accounts/templates/accounts/signup.html, accounts/templates/accounts/update.html, static/accounts/css/signup.css, static/accounts/css/update.css
=> [UPDATE] accounts/signup, update.html

accounts/templates/accounts/profile.html, paints/templates/paints/index.html, static/accounts/css/profile.css, static/base/css/base.css, static/base/css/common.css, static/paints/css/index.css, static/posts/css/detail.css, templates/base.html
신고 베이스 띄우기, 채팅 네비추가, 프로필 페이지 내 내이동으로 신고로가기 버튼 추가 등
=> [UPDATE]base_profile

posts/templates/posts/anonymous_detail.html, posts/templates/posts/detail.html, static/posts/css/detail.css
=> [UPDATE] posts/detail.html, anonymous/detail.html

chat/consumers.py, posts/templates/posts/detail.html, static/base/css/base.css, static/posts/css/detail.css, templates/aboutus.html
=> [UPDATE]post/detail_aboutus

posts/views.py
=> [UPDATE] superuser-view

posts/views.py
=> [UPDATE] view-detail 수정

posts/templates/posts/anonymous.html, posts/templates/posts/index.html
=> [UPDATE] posts-profile-image

chat/consumers.py, chat/templates/chat/room.html, posts/models.py
=> [UPDATE] chat-name,profile_image

accounts/templates/accounts/profile.html, static/accounts/css/profile.css, static/base/css/common.css
=> Revert "profile.html 반응형 추가"
